name: Deploy GitHub

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up pnpm
        uses: pnpm/setup@v3
        # with:
        #   version: 11.27.1
        #   runtime: node@22
        #   cache: true
        #   install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm run lint

      - name: Run build
        run: pnpm web build

      - name: Setup pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: apps/web/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
